---

- name: create domain directories
  file:
    path: /organisation/websites/{{ domain_tld }}/{{ domain_sub }}/{{ item }}
    state: directory
  with_items:
  - logs
  - public_html
  - tmp

- name: create user
  user:
    name: "{{ domain_user }}"
    shell: /bin/bash
    home: "/organisation/websites/{{ domain_tld }}"

- name: set permissions
  file:
    path: "/organisation/websites/{{ domain_tld }}"
    owner: "{{ domain_user }}"
    group: "{{ domain_user }}"
    mode: 0750
    state: directory
    recurse: yes

- name: add www-data to new user group
  user:
    name: www-data
    groups: "{{ domain_user }}" # must be groups to not change the primary group
    append: yes
