#
# style bash and MOTD
#
# RUN THIS MANUALLY FIRST to name the server and adjust the timezone:
# hostnamectl set-hostname server.organisation.com && ln -sf /usr/share/zoneinfo/Europe/London /etc/localtime && shutdown -r now;
#
#
# add sendgrid settings to postfix, watch out for the duplicate relayhost
#
# may need to force ipv4 in /etc/postfix/main.cf
# - inet_protocols = ipv4
# - smtp_address_preference = ipv4
#

---

- name: ensure python is installed (particularly for AWS EC2)
  raw: test -e /usr/bin/python || (apt update && apt install -y python-minimal)

- name: apt update
  apt: update_cache=yes

- name: apt upgrade
  command: apt-get upgrade -y

# debconf-set-selections <<< "postfix postfix/mailname string $(hostname)" && debconf-set-selections <<< "postfix postfix/main_mailer_type string 'Internet Site'" && apt install -y postfix

- name: set postfix hostname
  debconf:
    name: postfix
    question: postfix/mailname
    vtype: string
    value: "$(hostname)"

- name: set postfix type
  debconf:
    name: postfix
    question: postfix/main_mailer_type
    vtype: string
    value: "'Internet Site'"

- name: install standard packages
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
  - postfix
  - git
  - perl                  #webmin
  - libnet-ssleay-perl    #webmin
  - openssl               #webmin
  - libauthen-pam-perl    #webmin
  - libpam-runtime        #webmin
  - libio-pty-perl        #webmin
  - apt-show-versions     #webmin
  - python                #webmin
  - apticron
  - ntp
  - logwatch
  - zip
  - sudo
  - rsync
  - aptitude
  - fail2ban
  - htop
  - curl
  - wget
  - needrestart # great on servers, not that useful on WSL

- name: generate SSH key and authenticate with bitbucket
  shell: |
    ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa > /dev/null;
    curl --user {{ bbuser }}:{{ bbpass }} --data-urlencode key@${HOME}/.ssh/id_rsa.pub --data "label=$(hostname)" https://bitbucket.org/api/1.0/repositories/{{ bbuser }}/organisationserverconfig/deploy-keys

- name: make organisation and git directories
  file:
    path: /organisation/git
    state: directory

- name: add bitbucket ssh key to system
  shell: ssh-keyscan bitbucket.org >> /etc/ssh/ssh_known_hosts
  args:
    creates: /etc/ssh/ssh_known_hosts

- name: clone git repo
  git:
    repo: git@bitbucket.org:{{ bbuser }}/organisationserverconfig.git
    dest: /organisation/git

- name: retrieve webmin deb file
  get_url:
    url: wget http://www.webmin.com/download/deb/webmin-current.deb
    dest: /tmp/webmin-current.deb
    mode: 0755

- name: install webmin
  command: dpkg --install /tmp/webmin-current.deb

- name: change webmin ports
  command: "sed --in-place {{ item }} /etc/webmin/miniserv.conf"
  with_items:
  - 's/port=10000/port=30303/'
  - 's/listen=10000/listen=30303/'
  notify: restart webmin

- name: change apticron email address
  command: sed --in-place 's/EMAIL="root"/EMAIL="maintenance@example.com"/' /etc/apticron/apticron.conf

# - name: switch NTP to UK servers
#   shell: sed --in-place 's/\.debian\.pool\.ntp\.org/\.uk\.pool\.ntp\.org/' /etc/ntp.conf && systemctl restart ntp

- name: update logwatch settings to send high detailed emails
  command: "sed --in-place {{ item }} /usr/share/logwatch/default.conf/logwatch.conf"
  with_items:
  - "'s/Output = stdout/Output = mail/'"
  - "'s/MailTo = root/MailTo = maintenance@example.com/'"
  - "'s/Detail = Low/Detail = High/'"

# update the following logwatch files with custom log location
# /usr/share/logwatch/default.conf/logfiles/http.conf
# /usr/share/logwatch/default.conf/logfiles/http-error.conf

- name: update logwatch cron to include email settings too, just in case
  command: "sed --in-place 's/logwatch --output mail/logwatch --mailto maintenance@example.com/' /etc/cron.daily/00logwatch"

- name: apply custom fail2ban settings
  file:
    state: link
    src: /organisation/git/config/fail2ban/jail.local
    dest: /etc/fail2ban/jail.local

# http://blog.bobbyallen.me/2013/02/03/how-to-redirect-local-root-mail-to-an-external-email-address-on-linux/
- name: send root email to us
  shell: 'echo "root: maintenance@example.com" >> /etc/aliases && newaliases && systemctl restart postfix'

# floppy disk hilarity
# lsmod | grep -i floppy (prove floppy driver loaded)
# nano /etc/modprobe.d/blacklist (add "blacklist floppy")
# - might be blacklist.conf?
# reboot
# http://www.cyberciti.biz/faq/linux-end_request-ioerror-dev-fd0-sector0/