#
# ansible-playbook playbooks/create-apache-vhost.yml -i playbooks/inventory.txt
#

---

- hosts: localhost
  gather_facts: no
  remote_user: root
  become: no
  vars_prompt:
  - name: "domain_tld"
    prompt: "What is the TLD (i.e. example.com)?"
    private: no
  - name: "domain_sub"
    prompt: "What is the site (i.e. www)?"
    private: no
  - name: "domain_user"
    prompt: "What is the server user (i.e. example)?"
    private: no
  tasks:

  - name: generate virtualhost file
    local_action:
      module: template
      src: templates/apachevhost.conf.j2
      dest: "../config/apache/sites/{{ domain_tld }}-{{ domain_sub }}.conf"

  - name: generate pool file
    local_action:
      module: template
      src: templates/fpmpool.j2
      dest: "../config/fpm/pools/{{ domain_tld }}-{{ domain_sub }}.conf"
